import React from 'react';
import { BookOpen, BrainCircuit, CheckCircle, ShieldCheck, Sparkles } from 'lucide-react';
import SEO from '../components/SEO';
import Navbar from '../components/home/Navbar';
import Footer from '../components/home/Footer';
import AgenticAIQuiz, { QuizQuestion } from '../components/challenge/AgenticAIQuiz';
import { openLeadModal } from '../services/leadModal';

const questions: QuizQuestion[] = [
  {
    id: 1,
    prompt: 'According to the AI maturity curve in the training, what is the key shift from chatbots to Agentic AI?',
    options: ['From using smaller models to larger models', 'From conversation to coordinated execution', 'From typing prompts to using voice input', 'From free tools to paid tools'],
    answerIndex: 1,
    explanation: 'The key shift is from simply conversing with AI to coordinating AI systems that can plan, use tools, and execute bounded workflows.',
  },
  {
    id: 2,
    prompt: 'Which stage best describes traditional chatbots?',
    options: ['They coordinate multiple agents across departments', 'They answer questions but do not execute real work', 'They autonomously approve payments', 'They manage company workflows end-to-end'],
    answerIndex: 1,
    explanation: 'Traditional chatbots mainly answer questions. They do not usually plan, operate tools, or execute real work across systems.',
  },
  {
    id: 3,
    prompt: 'What makes an AI agent different from ordinary ChatGPT use?',
    options: ['It only writes longer answers', 'It can plan, use tools, and take action within boundaries', 'It does not need any user instructions', 'It always replaces human approval'],
    answerIndex: 1,
    explanation: 'An AI agent can plan steps, use tools, and take action, but it still needs clear boundaries, context, and human oversight for higher-risk decisions.',
  },
  {
    id: 4,
    prompt: 'In the training, Agentic AI requires control layers because:',
    options: ['Better prompts alone are enough for safe adoption', 'Agents can act across systems, so access and decision authority must be managed', 'AI agents should be allowed to work without limits', 'Governance is only needed after something fails'],
    answerIndex: 1,
    explanation: 'Because agents can act across systems, organisations need controls for access, approvals, decision authority, and accountability.',
  },
  {
    id: 5,
    prompt: 'Which of the following best describes an AI workflow?',
    options: ['A random conversation with an AI chatbot', 'A step-by-step process with defined inputs, actions, outputs, and review', 'A folder for storing old prompts', 'A single answer generated by AI'],
    answerIndex: 1,
    explanation: 'A workflow has defined inputs, actions, outputs, and review points, rather than a one-off conversation or answer.',
  },
  {
    id: 6,
    prompt: 'What is “context engineering” as taught in the training?',
    options: ['Writing longer prompts with more words', 'Selecting the right source material, constraints, examples, and goals for the AI', 'Asking the AI to ignore all previous information', 'Using only technical jargon in prompts'],
    answerIndex: 1,
    explanation: 'Context engineering means shaping what the AI can see and use: relevant source material, constraints, examples, goals, and boundaries.',
  },
  {
    id: 7,
    prompt: 'What is the context window?',
    options: ['The AI’s working memory — what it can see at one time', 'The computer screen used to display the chatbot', 'A permanent database of everything the AI has learned', 'A company file server'],
    answerIndex: 0,
    explanation: 'The context window is the AI’s working memory for the current interaction: the information it can see at one time.',
  },
  {
    id: 8,
    prompt: 'What is “context rot”?',
    options: ['When the AI becomes better as a conversation gets longer', 'When response quality degrades because the conversation becomes too long or cluttered', 'When the AI refuses to answer all questions', 'When a file is deleted from the project folder'],
    answerIndex: 1,
    explanation: 'Context rot happens when a conversation becomes too long, noisy, or cluttered, causing useful signal and instructions to degrade.',
  },
  {
    id: 9,
    prompt: 'Why can auto-compacting create problems?',
    options: ['It always deletes all files from the computer', 'It may summarise older conversation details and lose useful nuance', 'It prevents users from sending new prompts', 'It disables all AI tools permanently'],
    answerIndex: 1,
    explanation: 'Auto-compacting can preserve the gist but lose nuance, exact instructions, examples, or decision details that matter later.',
  },
  {
    id: 10,
    prompt: 'In the CRISP prompting framework, what does “C” stand for?',
    options: ['Control', 'Context', 'Coding', 'Compliance'],
    answerIndex: 1,
    explanation: 'In CRISP, “C” stands for Context: give the AI the relevant background and task conditions before asking it to produce output.',
  },
  {
    id: 11,
    prompt: 'Which prompt best follows the CRISP idea?',
    options: ['“Make this better.”', '“Help me with this.”', '“Act as a communications advisor. Rewrite this client update in 150–180 words, using a professional and reassuring tone.”', '“Do something useful.”'],
    answerIndex: 2,
    explanation: 'The best prompt gives role, task, output length, audience/tone, and constraints, making it much more actionable than a vague instruction.',
  },
  {
    id: 12,
    prompt: 'What is Plan Mode in Codex used for?',
    options: ['To force Codex to delete all previous work', 'To make Codex interview the user and create a structure before modifying files', 'To prevent Codex from asking questions', 'To skip planning and immediately write code'],
    answerIndex: 1,
    explanation: 'Plan Mode helps Codex clarify requirements, structure work, and propose a plan before making file changes.',
  },
  {
    id: 13,
    prompt: 'What is a Codex project folder?',
    options: ['A random online chatroom', 'A dedicated local workspace where Codex can read, edit, and run project files', 'A Microsoft Teams channel', 'A static PDF document'],
    answerIndex: 1,
    explanation: 'A Codex project folder is a local workspace containing the files Codex can inspect, edit, run, and verify.',
  },
  {
    id: 14,
    prompt: 'What are Codex Skills?',
    options: ['Reusable instruction playbooks that teach Codex how to perform specific workflows', 'Secret model weights stored inside the AI', 'Browser extensions for watching videos', 'Passwords used to access company systems'],
    answerIndex: 0,
    explanation: 'Skills are reusable playbooks for recurring workflows, helping Codex perform tasks consistently without re-prompting every detail.',
  },
  {
    id: 15,
    prompt: 'A good skill should be:',
    options: ['Broad, vague, and inspirational', 'Narrow, procedural, and testable', 'Hidden from the user', 'Dependent on constantly changing external webpages'],
    answerIndex: 1,
    explanation: 'A good skill is narrow enough to apply reliably, procedural enough to execute, and testable enough to verify.',
  },
  {
    id: 16,
    prompt: 'What is the main purpose of turning a repeated workflow into a skill?',
    options: ['To avoid documenting the process', 'To make reliable execution less dependent on perfect prompting each time', 'To remove the need for any human review', 'To make every task more complicated'],
    answerIndex: 1,
    explanation: 'Skills reduce dependency on perfect one-off prompting by capturing reliable steps, checks, and pitfalls for repeated workflows.',
  },
  {
    id: 17,
    prompt: 'In the training, what is the difference between memory and a knowledge base?',
    options: ['They are exactly the same', 'Memory is what the agent remembers about the user or workflow; a knowledge base is what the agent can look up', 'A knowledge base is only for images', 'Memory is always more accurate than source documents'],
    answerIndex: 1,
    explanation: 'Memory stores durable context about the user or workflow. A knowledge base is an external source the agent can retrieve from when needed.',
  },
  {
    id: 18,
    prompt: 'Which statement best describes good AI memory?',
    options: ['Store everything forever', 'Retrieve the right prior context into the current context window', 'Avoid using past information', 'Let the model secretly learn the company’s entire job'],
    answerIndex: 1,
    explanation: 'Good AI memory is selective: it retrieves the right prior context into the current context window rather than storing or injecting everything.',
  },
  {
    id: 19,
    prompt: 'In agent connectivity, what does MCP stand for?',
    options: ['Model Context Protocol', 'Machine Coding Platform', 'Manual Control Process', 'Memory Cache Programme'],
    answerIndex: 0,
    explanation: 'MCP stands for Model Context Protocol, a standard pattern for connecting models and agents to external tools or context sources.',
  },
  {
    id: 20,
    prompt: 'What is the key governance lesson from the training on Agentic AI safety?',
    options: ['Governance is only about writing better prompts', 'Old AI gave wrong answers, but agentic AI can take wrong actions, so access, approval, and accountability matter', 'All agents should have full system access', 'Human review should be removed once automation starts'],
    answerIndex: 1,
    explanation: 'Agentic AI raises the stakes because systems may take actions, not just produce answers. Access control, approvals, and accountability become essential.',
  },
];

const pillars = [
  { icon: BrainCircuit, label: 'AI maturity', detail: 'Chatbot → GenAI → Workflow → Agent → Agentic AI' },
  { icon: BookOpen, label: 'Context engineering', detail: 'Context window, context rot, CRISP prompting' },
  { icon: Sparkles, label: 'Codex workflows', detail: 'Project folders, Plan Mode, skills, plugins, mini-apps' },
  { icon: ShieldCheck, label: 'Governance', detail: 'Bounding, HITL checkpoints, access, accountability' },
];

const AgenticAIChallengePage: React.FC = () => {
  const handleLeadClick = (_score: number, _resultTitle: string) => {
    openLeadModal('course_page_cta', 'reserve_seat', {
      page: 'agentic_ai_challenge',
      position: 'challenge_results_guidance',
      ctaLabel: 'get_course_guidance',
      preferredIntake: 'Agentic AI Challenge result follow-up',
      cohortCode: 'agentic-ai-challenge',
    });
  };

  return (
    <div className="font-body text-charcoal bg-primary min-h-screen flex flex-col">
      <SEO
        title="Agentic AI Challenge | Nexius Academy"
        description="Take the Nexius Academy Agentic AI Challenge: a 20-question quiz covering AI maturity, context engineering, Codex workflows, memory, MCP, and governance."
        canonical="/assessments"
        ogType="website"
      />
      <Navbar />

      <main className="flex-grow">
        <section className="relative overflow-hidden bg-primary pt-32 pb-16 md:pt-40 md:pb-24">
          <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_left,rgba(0,202,186,0.26),transparent_34%),radial-gradient(circle_at_bottom_right,rgba(255,107,44,0.16),transparent_28%),linear-gradient(135deg,#101827_0%,#1D2A4D_55%,#101827_100%)]" />
          <div className="absolute left-8 top-24 h-56 w-56 rounded-full bg-accent/20 blur-3xl" />
          <div className="absolute bottom-12 right-8 h-72 w-72 rounded-full bg-brand-orange/20 blur-3xl" />

          <div className="container relative z-10 mx-auto px-6">
            <div className="mx-auto mb-10 max-w-4xl text-center">
              <div className="mb-5 inline-flex items-center gap-2 rounded-full border border-accent/30 bg-white/10 px-4 py-2 text-sm font-bold uppercase tracking-[0.18em] text-accent">
                <CheckCircle size={16} />
                Nexius Academy Training Quiz
              </div>
              <h1 className="font-heading text-4xl font-bold leading-tight text-white md:text-6xl">
                Agentic AI Challenge
              </h1>
              <p className="mx-auto mt-5 max-w-3xl text-lg leading-relaxed text-slate-300 md:text-xl">
                Test your understanding of the Agentic AI Foundation training concepts — from AI evolution and context engineering to Codex, skills, MCP, memory, and safe human-in-the-loop governance.
              </p>
            </div>

            <AgenticAIQuiz questions={questions} onLeadClick={handleLeadClick} />
          </div>
        </section>

        <section className="bg-white py-16 md:py-20">
          <div className="container mx-auto px-6">
            <div className="mx-auto max-w-3xl text-center">
              <div className="mb-3 text-sm font-bold uppercase tracking-[0.18em] text-accent">What this challenge covers</div>
              <h2 className="font-heading text-3xl font-bold text-primary md:text-4xl">Built from the Agentic AI Foundation training themes</h2>
              <p className="mt-4 text-gray-600">
                The quiz is designed as a practical diagnostic, not a trivia game. Each question maps to concepts learners encounter in the foundation workshop.
              </p>
            </div>
            <div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">
              {pillars.map((pillar) => {
                const Icon = pillar.icon;
                return (
                  <article key={pillar.label} className="rounded-3xl border border-gray-100 bg-neutral p-6 shadow-sm">
                    <div className="mb-5 flex h-12 w-12 items-center justify-center rounded-2xl bg-accent/10 text-accent">
                      <Icon size={24} />
                    </div>
                    <h3 className="font-heading text-lg font-bold text-primary">{pillar.label}</h3>
                    <p className="mt-2 text-sm leading-relaxed text-gray-600">{pillar.detail}</p>
                  </article>
                );
              })}
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
};

export default AgenticAIChallengePage;
